package com.chatapp.client.enums;

/**
 * Enum định nghĩa các loại gói tin trao đổi giữa Client và Server
 */
public enum PacketType {
    // Authentication
    REGISTER_REQUEST,
    REGISTER_RESPONSE,
    LOGIN_REQUEST,
    LOGIN_RESPONSE,
    LOGOUT_REQUEST,

    // User Management
    UPDATE_PROFILE_REQUEST,
    UPDATE_PROFILE_RESPONSE,
    UPDATE_STATUS_REQUEST,
    UPDATE_STATUS_RESPONSE,
    STATUS_CHANGE_NOTIFICATION,

    // Friend Management
    SEARCH_USER_REQUEST,
    SEARCH_USER_RESPONSE,
    SEND_FRIEND_REQUEST,
    FRIEND_REQUEST_NOTIFICATION,
    ACCEPT_FRIEND_REQUEST,
    REJECT_FRIEND_REQUEST,
    GET_FRIEND_LIST_REQUEST,
    GET_FRIEND_LIST_RESPONSE,
    GET_FRIEND_REQUESTS_REQUEST,
    GET_FRIEND_REQUESTS_RESPONSE,
    GET_USER_PROFILE_REQUEST,
    GET_USER_PROFILE_RESPONSE,

    // Messaging
    SEND_MESSAGE,
    MESSAGE_NOTIFICATION,
    GET_MESSAGE_HISTORY_REQUEST,
    GET_MESSAGE_HISTORY_RESPONSE,

    // Group Management
    CREATE_GROUP_REQUEST,
    CREATE_GROUP_RESPONSE,
    GET_GROUP_LIST_REQUEST,
    GET_GROUP_LIST_RESPONSE,
    JOIN_GROUP_REQUEST,
    LEAVE_GROUP_REQUEST,
    ADD_MEMBER_TO_GROUP_REQUEST,
    GROUP_NOTIFICATION,

    // File Transfer
    FILE_TRANSFER_REQUEST,
    FILE_TRANSFER_RESPONSE,
    FILE_CHUNK,
    FILE_TRANSFER_COMPLETE,

    // Call Signaling
    CALL_OFFER,
    CALL_ANSWER,
    CALL_REJECT,
    CALL_END,
    CALL_NOTIFICATION,

    // General
    ERROR,
    SUCCESS,
    HEARTBEAT
}
